# Generated by Django 4.0.3 on 2022-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='사진')),
                ('source', models.TextField(blank=True, verbose_name='사진 출처')),
                ('body', models.TextField(verbose_name='전할 말')),
            ],
        ),
    ]
