# Generated by Django 4.0.3 on 2022-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='letter_paper',
            field=models.CharField(default='ic.bottle_heart', max_length=30, verbose_name='편지지'),
        ),
    ]
