# Generated by Django 4.0.3 on 2022-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('source', models.TextField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
