# Generated by Django 4.0.3 on 2022-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_post_letter_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
        migrations.AlterField(
            model_name='post',
            name='letter_paper',
            field=models.CharField(default='ic_bottle_heart', max_length=30, verbose_name='편지지'),
        ),
    ]
