# Generated by Django 4.0.3 on 2022-04-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_remove_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
